#!/bin/bash
for folder in */
do
cd ${folder}
python3 setup.py check sdist bdist
python3 setup.py sdist bdist_wheel
python3 -m twine upload --skip-existing --repository-url https://gitlab.com/api/v4/projects/19185895/packages/pypi -u "$PYPI_USER" -p "$PYPI_PASSWORD" dist/*
cd ..
done
